return {
	"catppuccin/nvim",
	name = "catppuccin",
	commit = "8076ba30b74b5902b3fed1e5176855158c5ba551",
	priority = 1000,
	config = function()
		require("catppuccin").setup({
			show_end_of_buffer = false,
			no_italic = true,
			float = {
				solid = false,
				transparent = false,
			},
			custom_highlights = function(colors)
				return {
					["@lsp.typemod.keyword.async"] = { link = "@keyword.coroutine" },
					["@lsp.typemod.macro.defaultLibrary"] = { link = "@function.builtin" },
					["@lsp.typemod.method.defaultLibrary"] = { link = "@function.builtin" },
					["@lsp.typemod.operator.injected"] = { link = "@operator" },
					["@lsp.typemod.string.injected"] = { link = "@string" },
					["@lsp.typemod.type.defaultLibrary"] = { link = "@type.builtin" },
					["@lsp.typemod.variable.defaultLibrary"] = { link = "@variable.builtin" },
					["@lsp.typemod.variable.injected"] = { link = "@variable" },
					["@lsp.type.boolean"] = { link = "@boolean" },
					["@lsp.type.builtinType"] = { link = "@type.builtin" },
					["@lsp.type.comment"] = { link = "@comment" },
					["@lsp.type.enum"] = { link = "@type" },
					["@lsp.type.enumMember"] = { link = "@constant" },
					["@lsp.type.escapeSequence"] = { link = "@string.escape" },
					["@lsp.type.formatSpecifier"] = { link = "@punctuation.special" },
					["@lsp.type.interface"] = { fg = colors.flamingo },
					["@lsp.type.keyword"] = { link = "@keyword" },
					["@lsp.type.namespace"] = { link = "@module" },
					["@lsp.type.number"] = { link = "@number" },
					["@lsp.type.operator"] = { link = "@operator" },
					["@lsp.type.parameter"] = { link = "@parameter" },
					["@lsp.type.property"] = { link = "@property" },
					["@lsp.type.selfKeyword"] = { link = "@variable.builtin" },
					["@lsp.type.typeAlias"] = { link = "@type.definition" },
					["@lsp.type.unresolvedReference"] = { link = "@error" },
					["@lsp.type.variable"] = {}, -- use treesitter styles for regular variables
					["@lsp.typemod.class.defaultLibrary"] = { link = "@type.builtin" },
					["@lsp.typemod.enum.defaultLibrary"] = { link = "@type.builtin" },
					["@lsp.typemod.enumMember.defaultLibrary"] = { link = "@constant.builtin" },
				}
			end,
			term_colors = true,
			flavour = "mocha",
			integrations = {
				colorful_winsep = true,
				native_lsp = {
					enabled = true,
					inlay_hints = {
						background = true,
					},
					underlines = {
						errors = { "underdashed" },
						information = { "underdashed" },
						hints = { "underdashed" },
						warnings = { "underdashed" },
					},
				},
				blink_cmp = true,
				dashboard = true,
				window_picker = true,
				vimwiki = true,
				treesitter_context = true,
				treesitter = true,
				snacks = true,
				barbar = false,
				fzf = true,
				gitgraph = true,
				gitgutter = true,
				gitsigns = true,
				markdown = true,
				markview = true,
				render_markdown = true,
				rainbow_delimiters = true,
				telescope = true,
				which_key = true,
				nvimtree = true,
				notify = true,
				nvim_surround = true,
				vim_sneak = true,
				neogit = true,
				semantic_tokens = true,
			},
		})
		vim.cmd.colorscheme("catppuccin")
	end,
}
