vim.keymap.set("i", "<C-s>", "<cmd>w<CR>")
vim.keymap.set("n", "<C-s>", "<cmd>w<CR>")
vim.keymap.set("n", "<C-q>", "<cmd>qa<CR>")
vim.keymap.set("c", "<C-q>", "<cmd>qa<CR>")
vim.keymap.set("n", "<leader>qb", "<cmd>BufferClose<CR>")
vim.keymap.set("v", "<leader>qb", "<cmd>BufferClose<CR>")
vim.keymap.set("n", "<leader>qw", "<cmd>q<CR>")
vim.keymap.set("v", "<leader>qw", "<cmd>q<CR>")
vim.keymap.set("n", "<C-f>", "<cmd>NvimTreeToggle<CR>")
vim.keymap.set("n", "<A-Up>", ":m-2<CR>", { noremap = true, silent = true })
vim.keymap.set("n", "<A-Down>", ":m+<CR>", { noremap = true, silent = true })
vim.keymap.set("n", "<C-/>", "gcc", {remap = true})
vim.keymap.set("v", "<C-/>", "gc", {remap = true})
vim.keymap.set("i", "<C-/>", function() 
    vim.cmd("normal gcc")
end, {remap = true})
vim.keymap.set({"n", "v", "i"}, "<A-Right>", function() 
    vim.cmd("bnext")
end)
vim.keymap.set({"n", "v", "i"}, "<A-Left>", function() 
    vim.cmd("bprevious")
end)